version: "3"

services:
  client:
    image: krtisheva/client
    ports:
      - 80:80
    depends_on:
      - server
  server:
    image: krtisheva/server
    command: node index.js
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: krtisheva/database
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'web_l1'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432


